// This file is generated by @reposcope/cli

declare module '@/lib/charts-types/widgets-definitions' {
  interface WidgetsDefinitions {
    /**
     * Analyze User Dashboard Stats
     */
    '@reposcope/widget-compose-user-dashboard-stats': {
      isPrivate: false,
      params: {
        user_id: number // Analyzing User
      }
    }
    
    /**
     * Identify the top contributors with their contribution counts in a repository over the last 28 days. 
     */
    '@reposcope/widget-compose-recent-top-contributors': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
      }
    }
    
    /**
     * Identify the most active contributors in a repository over the past 28 days. Recognize and engage with individuals who have made significant contributions during this period.
     */
    '@reposcope/widget-compose-recent-active-contributors': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        limit: number // Limit
      }
    }
    
    /**
     * Top repositories by stars for an organization
     */
    '@reposcope/widget-compose-org-stars-top-repos': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Ranking of repos with most proactive Pull Request Review responses of an organization
     */
    '@reposcope/widget-compose-org-pull-requests-open-to-review': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Activity ratio of an organization
     */
    '@reposcope/widget-compose-org-productivity-ratio': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        activity?: string // Activity type
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Participants roles ratio of an organization
     */
    '@reposcope/widget-compose-org-participants-roles-ratio': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Participants trends for an organization
     */
    '@reposcope/widget-compose-org-participants-growth': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Repo
        activity?: string // Activity type
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * [Overview] Pull Requests/Issues/Reviews stats for an organization
     */
    '@reposcope/widget-compose-org-overview-stats': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        activity?: string // Activity type
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Overview of stars earned for an organization
     */
    '@reposcope/widget-compose-org-overview-stars': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Most engaged people in an organization
     */
    '@reposcope/widget-compose-org-engagement-scatter': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Ranking of repos with the commit code changes in an organization
     */
    '@reposcope/widget-compose-org-code-changes-top-repositories': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Measure and compare first response times to issues/PRs. Identify bottlenecks and assess response efficiency.
     */
    '@reposcope/widget-compose-org-activity-open-to-first-response': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        activity?: string // Type
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Measure and compare completion time to issues/prs. Identify bottlenecks and assess response efficiency.
     */
    '@reposcope/widget-compose-org-activity-open-to-close': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        activity?: string // Type
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Ranking of repos with the most new activities in an organization
     */
    '@reposcope/widget-compose-org-activity-new-ranking': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        activity?: string // Type
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Visualize and compare the geographic distribution of stars/participants worldwide.
     */
    '@reposcope/widget-compose-org-activity-map': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        activity?: string // Activity type
        role?: string // Role type
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Activity trends for an organization
     */
    '@reposcope/widget-compose-org-activity-growth-total': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Repo
        activity?: string // Activity type
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Analyze company affiliations of repository stargazers and participants.
     */
    '@reposcope/widget-compose-org-activity-company': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        activity?: string // Activity type
        role?: string // Role type
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Ranking of repos with the most active contributors in an organization
     */
    '@reposcope/widget-compose-org-activity-active-ranking': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        activity?: string // Type
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Show the active/new contributors of an organization
     */
    '@reposcope/widget-compose-org-active-contributors': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        activity?: string // Activity type
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Analyze the overall repository performance in the last 28 days with stars, active contributors, pull requests, and issues.
     */
    '@reposcope/widget-compose-last-28-days-stats': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
      }
    }
    
    /**
     * Analyze the collaborative efficiency of a repository, including pull request merge rate, review rate, and issue closed rate, over the last 28 days.
     */
    '@reposcope/widget-compose-last-28-days-collaborative-productivity': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
      }
    }
    
    /**
     * Analyze a developer's recent focus by identifying actively engaged repositories in the last 28 days.
     */
    '@reposcope/widget-compose-currently-working-on': {
      isPrivate: false,
      params: {
        user_id: number // Analyzing User
        activity_type: string // Activity event type
      }
    }
    
    /**
     * Show all the contributors of the repo.
     */
    '@reposcope/widget-compose-contributors': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        limit: number // Limit
      }
    }
    
    /**
     * Analyze all different types of events triggered by activity on GitHub within a repository over the last 28 days.
     */
    '@reposcope/widget-compose-activity-trends': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        from?: number // Start date
        to?: number // End date
      }
    }
    
    /**
     * Rank a group of repositories within the same technical field based on star count, pull request count, pull request creators, and issue count.
     */
    '@reposcope/widget-collection-annually-ranking': {
      isPrivate: false,
      params: {
        collection_id: number // Collection
        activity?: string // Activity type
      }
    }
    
    /**
     * Basic radar chart visualization
     */
    '@reposcope/basic-radar-chart': {
      isPrivate: false,
      params: {
        start: any // Start time
        end: any // End time
        axis_field: string // Axis field
        value_field: string // Value field
        label_field: string // Label field
      }
    }
    
    /**
     * Basic bubbles chart visualization
     */
    '@reposcope/basic-bubbles-chart': {
      isPrivate: false,
      params: {
        start: any // Start time
        end: any // End time
        axis_field: string // Axis field
        value_field: string // Value field
        label_field: string // Label field
      }
    }
    
    /**
     * Show the contribution trends of a GitHub user.
     */
    '@reposcope/widget-analyze-user-contribution-trends': {
      isPrivate: false,
      params: {
        user_id: number // Analyzing User
      }
    }
    
    /**
     * Analyze and plot user contributions over time. Recognize peak periods of activity for different users.
     */
    '@reposcope/widget-analyze-user-contribution-time-distribution': {
      isPrivate: false,
      params: {
        user_id: number // Analyzing User
        period: string // Period
      }
    }
    
    /**
     * Visualize and compare the geographic distribution of stars worldwide.
     */
    '@reposcope/widget-analyze-repo-stars-map': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        vs_repo_id?: number // Comparing Repo
        activity?: string // Activity type
      }
    }
    
    /**
     * Analyze and compare historical trends in star count for the repository.
     */
    '@reposcope/widget-analyze-repo-stars-history': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        vs_repo_id?: number // Comparing Repo
      }
    }
    
    /**
     * Recent top contributors of a GitHub repository.
     */
    '@reposcope/widget-analyze-repo-recent-top-contributors': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
      }
    }
    
    /**
     * [Last 28 days Stats] Show the recent star history of a GitHub repository.
     */
    '@reposcope/widget-analyze-repo-recent-stars': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
      }
    }
    
    /**
     * [Last 28 days Stats] Show the recent PR history of a GitHub repository.
     */
    '@reposcope/widget-analyze-repo-recent-pull-requests': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
      }
    }
    
    /**
     * [Last 28 days Stats] Show the recent issue history of a GitHub repository.
     */
    '@reposcope/widget-analyze-repo-recent-issues': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
      }
    }
    
    /**
     * [Last 28 days Stats] Show the recent contributors of a GitHub repository.
     */
    '@reposcope/widget-analyze-repo-recent-contributors': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
      }
    }
    
    /**
     * [Last 28 days Stats] Show the recent commit history of a GitHub repository.
     */
    '@reposcope/widget-analyze-repo-recent-commits': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
      }
    }
    
    /**
     * [Last 28 days Stats] Show the recent collaborative productivity metrics.
     */
    '@reposcope/widget-analyze-repo-recent-collaborative-productivity-metrics': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        activity?: string // Activity type
      }
    }
    
    /**
     * Analyze and compare the count of code submissions in the repository, including pushes and commits.
     */
    '@reposcope/widget-analyze-repo-pushes-and-commits-per-month': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        vs_repo_id?: number // Comparing Repo
      }
    }
    
    /**
     * Examine and compare pull request sizes across different months.
     */
    '@reposcope/widget-analyze-repo-pull-requests-size-per-month': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        vs_repo_id?: number // Comparing Repo
      }
    }
    
    /**
     * Analyze and compare the open-to-merge time for pull requests.
     */
    '@reposcope/widget-analyze-repo-pull-request-open-to-merged': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        vs_repo_id?: number // Comparing Repo
      }
    }
    
    /**
     * Monitor and compare lines of code added/deleted per month.
     */
    '@reposcope/widget-analyze-repo-loc-per-month': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        vs_repo_id?: number // Comparing Repo
      }
    }
    
    /**
     * Analyze and compare the count of opened and closed issues within the repository. 
     */
    '@reposcope/widget-analyze-repo-issue-opened-and-closed': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        vs_repo_id?: number // Comparing Repo
      }
    }
    
    /**
     * Measure and compare first response times to issues. Identify bottlenecks and assess response efficiency.
     */
    '@reposcope/widget-analyze-repo-issue-open-to-first-responded': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        vs_repo_id?: number // Comparing Repo
      }
    }
    
    /**
     * Analyze and compare company affiliations of repository stargazers, pull request submitters, and issue creators.
     */
    '@reposcope/widget-analyze-repo-company': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        vs_repo_id?: number // Comparing Repo
        activity?: string // Activity type
      }
    }
    
    /**
     * Analyze and compare the preferred times for code submissions by individuals in repositories.
     */
    '@reposcope/widget-analyze-repo-commits-time-distribution': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        period: string // Period
        zone: number // Zone
        vs_repo_id?: number // Comparing Repo
      }
    }
    
    /**
     * Show the activity trends of a GitHub repository.
     */
    '@reposcope/widget-analyze-repo-activity-trends': {
      isPrivate: false,
      params: {
        repo_id: number // Analyzing Repo
        from?: number // From
        to?: number // To
      }
    }
    
    /**
     * Activity trends for an organization
     */
    '@reposcope/widget-analyze-org-recent-stats': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Repo
        activity?: string // Activity type
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Pull request review trends for an organization
     */
    '@reposcope/widget-analyze-org-recent-pr-review-stats': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Repo
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Ranking of repos with most proactive Pull Request Review responses of an organization
     */
    '@reposcope/widget-analyze-org-pull-requests-open-to-review': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
      }
    }
    
    /**
     * Most engaged people in an organization
     */
    '@reposcope/widget-analyze-org-engagement-scatter': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
      }
    }
    
    /**
     * Analyze company affiliations of repository stargazers and participants.
     */
    '@reposcope/widget-analyze-org-company': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        activity?: string // Activity type
      }
    }
    
    /**
     * Commits Time Distribution of an Organization
     */
    '@reposcope/widget-analyze-org-commits-time-distribution': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        zone: number // Zone
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Measure and compare first response times to issues/PRs. Identify bottlenecks and assess response efficiency.
     */
    '@reposcope/widget-analyze-org-activity-open-to-first-response': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        activity?: string // Type
      }
    }
    
    /**
     * Measure and compare completion time to issues/prs. Identify bottlenecks and assess response efficiency.
     */
    '@reposcope/widget-analyze-org-activity-open-to-close': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        activity?: string // Type
      }
    }
    
    /**
     * Visualize and compare the geographic distribution of stars/participants worldwide.
     */
    '@reposcope/widget-analyze-org-activity-map': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        activity?: string // Activity type
      }
    }
    
    /**
     * Activity efficiency metrics for an organization
     */
    '@reposcope/widget-analyze-org-activity-efficiency': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Org
        period: string // Period
        activity?: string // Type
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Ranking of repos with the most avtivities in an organization
     */
    '@reposcope/widget-analyze-org-activity-action-top-repos': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Repo
        activity?: string // Activity type
        period: string // Period
        repo_ids?: any // Repo
      }
    }
    
    /**
     * Activity action type ratio for an organization
     */
    '@reposcope/widget-analyze-org-activity-action-ratio': {
      isPrivate: false,
      params: {
        owner_id: number // Analyzing Repo
        activity?: string // Activity type
        period: string // Period
      }
    }
    
  }
}
